"""
__     __        _  _      _         _
\ \   / /  __ _ | |(_)  __| |  __ _ | |_   ___   _ __
 \ \ / /  / _` || || | / _` | / _` || __| / _ \ | '__|
  \ V /  | (_| || || || (_| || (_| || |_ | (_) || |
   \_/    \__,_||_||_| \__,_| \__,_| \__| \___/ |_|

This program validates a string sequence generated by another program.
The string should consist of messages, each be in the following format:
Message: <Magic |4|><Length|2|><Content|Length|><Checksum>

The entire sequence is in the following format:
Sequence: <Message><Seperator><Message><Seperator>...<Message><Seperator><EndBarker><Entire Seq.Checksum>
"""

import hashlib
from collections import OrderedDict


def validate(s: str):
    chsms = OrderedDict()
    i = 0
    cursum = 0
    lchunk = ''
    while True:
        cntr = 4
        chunk = s[i:i + cntr]
        i += cntr

        if chunk == 'X@y$':
            continue

        if lchunk and lchunk != chunk:
            chsms[lchunk] = cursum
            cursum = 0

        if chunk == 'A#<B':
            break

        lchunk = chunk
        cntr = int(s[i] + s[i + 1])
        i += 2

        chunk = s[i: i + cntr]
        i += cntr

        c = 0xFFFF
        for char in chunk:
            c ^= ord(char)
            for _ in range(8):
                if c & 0x0001:
                    c >>= 1
                    c ^= 0xA001
                else:
                    c >>= 1
        cursum += c

    chunk = ''.join(map(str, chsms.values()))
    calc = hashlib.md5(chunk.encode()).hexdigest()
    f = ''.join([s[i + _] for _ in range(32)])

    return str(f) == str(calc)


def main():
    s = 'wSr704zmT7X@y$w7Fj08afEqiiTzX@y$w7Fj03ugUX@y$djj108hPc6AB0zX@y$djj103AfVX@y$djj1035vhX@y$w7Fj02UwX@y$A#<Bc724dc57d014e57bc587d7002871c99d'
    if validate(s):
        print(':)')
    else:
        print(':(')

if __name__ == '__main__':
    main()
